import { Router } from "express";
import userRouter from "../controller/User/user-Router.js";
import franchiseRouter from "../controller/Franchise/franchise-Router.js";
import { providerCustomerRouter } from "../controller/Provider-Customer/provider-customer-Router.js";
import { productInventoryRouter } from "../controller/Product-Inventory/product-inventory-Router.js";
import { serviceRouter } from "../controller/Services/service-Router.js";
import { providerRouter } from "../controller/Provider/provider-Router.js";
import { subscriptionRouter } from "../controller/Subscription/subscription-Router.js";
import salesRouter from "../controller/Sales/sales-Router.js";
import purchaseRouter from "../controller/Purchase/purchase-Router.js";
import { expensesRouter } from "../controller/Expenses/expenses-Router.js";
import dashboardRouter from "../controller/Dashboard/dashboard-Router.js";
import { expenseCategoryRouter } from "../controller/Expense-Category/expense-category-Router.js";
import staffRouter from "../controller/Staff/staff-Router.js";
import { eWarrantyRouter } from "../controller/E-Warranty/e-warranty-Router.js";
import leadRouter from "../controller/Leads/lead-Router.js";
import appointmentRouter from "../controller/Appointments/appointment-Router.js";
import reportsRouter from "../controller/Reports/reports-Router.js";
import invoiceRouter from "../controller/Invoice/invoice-Router.js";
import quickSettingsRouter from "../controller/QuickSettings/quickSettingsRouter.js";
import { openInventoryRouter } from "../controller/Open-Inventory/open-inventory-Router.js";
import invoiceSettingsRouter from "../controller/InvoiceSettings/invoiceSettingsRouter.js";
import notificationsRouter from "../controller/Notifications/notification-Router.js";
// New routers for E-Warranty frontend compatibility
import ownerRouter from "../controller/Owner/owner-Router.js";
import customerRouter from "../controller/Customer/customer-Router.js";
import { dealerRouter } from "../controller/Dealer/dealer-Router.js";
import { warrantyClaimRouter } from "../controller/WarrantyClaim/warranty-claim-Router.js";
import { serviceCenterRouter } from "../controller/ServiceCenter/service-center-Router.js";
import { coinsRouter } from "../controller/Coins/coins-Router.js";
import superAdminRouter from "../controller/SuperAdmin/super-admin-Router.js";
import publicRouter from "../controller/Public/public-Router.js";

const router = Router();

router.use("/user", userRouter);
router.use("/provider", providerRouter);
router.use("/franchise", franchiseRouter);
router.use("/provider-customer", providerCustomerRouter);
router.use("/product-inventory", productInventoryRouter);
router.use("/service", serviceRouter);
router.use("/subscription", subscriptionRouter);
router.use("/purchase", purchaseRouter);
router.use("/expenses", expensesRouter);
router.use("/sales", salesRouter);
router.use("/dashboard", dashboardRouter);
router.use("/expense-category", expenseCategoryRouter);
router.use("/staff", staffRouter);
router.use("/e-warranty", eWarrantyRouter);
router.use("/reports", reportsRouter);
router.use("/lead", leadRouter);
router.use("/appointment", appointmentRouter);
router.use("/invoice", invoiceRouter);
router.use("/quick-settings", quickSettingsRouter);
router.use("/open-inventory", openInventoryRouter);
router.use("/invoice-settings", invoiceSettingsRouter);
router.use("/notifications", notificationsRouter);
// New routes for E-Warranty frontend compatibility
router.use("/owner", ownerRouter);
router.use("/customer", customerRouter);
router.use("/dealer", dealerRouter);
router.use("/warranty-claim", warrantyClaimRouter);
router.use("/service-center", serviceCenterRouter);
router.use("/coins", coinsRouter);
router.use("/super-admin", superAdminRouter);
router.use("/public", publicRouter);

export default router;
