import { ProviderProductWarrantyCode, ProviderWarrantyCustomer } from "../../../../prisma/db-models.js";
import { logger, returnResponse, returnError } from "../../../../services/logger.js";
import { StatusCodes } from "http-status-codes";

/**
 * Public endpoint: Verify warranty by code (no auth, no provider_id needed).
 * Real-world flow: Enter warranty code → get validity, status, product, expiry.
 * 
 * Searches in both:
 * 1. ProviderProductWarrantyCode (original warranty codes generated by owner)
 * 2. ProviderWarrantyCustomer (customer registrations - fallback if code not in #1)
 */
const verifyByCodeEndpoint = async (req, res) => {
    try {
        const codeInput = (req.body?.code || req.body?.warranty_code || req.query?.code || req.params?.code || "").toString().trim();
        logger.info(`verifyByCodeEndpoint - Searching for code: ${codeInput}`);
        
        if (!codeInput) {
            return returnError(res, StatusCodes.BAD_REQUEST, "Warranty code is required");
        }

        // First, try to find in ProviderProductWarrantyCode
        const code = await ProviderProductWarrantyCode.findFirst({
            where: { warranty_code: codeInput },
            include: {
                provider: {
                    select: {
                        id: true,
                        company_name: true,
                        company_logo: true,
                    },
                },
            },
        });

        if (code) {
            logger.info(`verifyByCodeEndpoint - Found in ProviderProductWarrantyCode`);
            
            if (code.is_deleted) {
                return returnError(res, StatusCodes.GONE, "This warranty code has been deactivated");
            }

            const registration = await ProviderWarrantyCustomer.findFirst({
                where: {
                    warranty_code: codeInput,
                    is_deleted: false,
                },
                select: {
                    id: true,
                    first_name: true,
                    last_name: true,
                    date_of_installation: true,
                    created_at: true,
                },
            });

            const now = new Date();
            const warrantyTo = code.warranty_to ? new Date(code.warranty_to) : null;
            const warrantyFrom = code.warranty_from ? new Date(code.warranty_from) : null;
            const isExpired = warrantyTo ? warrantyTo < now : false;
            let daysLeft = null;
            if (warrantyTo) {
                const diffMs = warrantyTo - now;
                daysLeft = diffMs > 0 ? Math.ceil(diffMs / (1000 * 60 * 60 * 24)) : 0;
            }

            return returnResponse(res, StatusCodes.OK, "Warranty verified", {
                valid: true,
                warranty_code: code.warranty_code,
                product_name: code.product_name,
                status: code.warranty_code_status,
                is_registered: !!registration,
                is_expired: isExpired,
                days_left: daysLeft,
                warranty_from: warrantyFrom ? warrantyFrom.toISOString() : null,
                warranty_to: warrantyTo ? warrantyTo.toISOString() : null,
                warranty_days: code.warranty_days,
                warranty_period_readable: code.warranty_period_readable,
                provider_id: code.provider?.id,
                provider_name: code.provider?.company_name,
                provider_logo: code.provider?.company_logo,
                serial_no: code.serial_no,
                registration_date: registration?.date_of_installation || registration?.created_at || null,
                customer_name: registration ? `${registration.first_name || ''} ${registration.last_name || ''}`.trim() : null,
            });
        }

        // Fallback: Search in ProviderWarrantyCustomer (customer registrations)
        logger.info(`verifyByCodeEndpoint - Not found in ProviderProductWarrantyCode, searching in ProviderWarrantyCustomer`);
        
        const customerRegistration = await ProviderWarrantyCustomer.findFirst({
            where: {
                warranty_code: codeInput,
                is_deleted: false,
            },
            include: {
                provider: {
                    select: {
                        id: true,
                        company_name: true,
                        company_logo: true,
                    },
                },
                provider_warranty_code: {
                    select: {
                        id: true,
                        warranty_code: true,
                        product_name: true,
                        warranty_code_status: true,
                        warranty_from: true,
                        warranty_to: true,
                        warranty_days: true,
                        warranty_period_readable: true,
                        serial_no: true,
                        is_deleted: true,
                    },
                },
            },
        });

        if (customerRegistration) {
            logger.info(`verifyByCodeEndpoint - Found in ProviderWarrantyCustomer`);
            
            const now = new Date();
            const linkedCode = customerRegistration.provider_warranty_code;
            
            // Calculate expiry based on linked code or registration date
            let warrantyTo = linkedCode?.warranty_to ? new Date(linkedCode.warranty_to) : null;
            let warrantyFrom = linkedCode?.warranty_from ? new Date(linkedCode.warranty_from) : null;
            const warrantyDays = linkedCode?.warranty_days;
            
            // If no warranty_to but has warranty_days and registration date, calculate it
            if (!warrantyTo && warrantyDays && customerRegistration.date_of_installation) {
                warrantyFrom = new Date(customerRegistration.date_of_installation);
                warrantyTo = new Date(warrantyFrom);
                warrantyTo.setDate(warrantyTo.getDate() + warrantyDays);
            }
            
            const isExpired = warrantyTo ? warrantyTo < now : false;
            let daysLeft = null;
            if (warrantyTo) {
                const diffMs = warrantyTo - now;
                daysLeft = diffMs > 0 ? Math.ceil(diffMs / (1000 * 60 * 60 * 24)) : 0;
            }

            return returnResponse(res, StatusCodes.OK, "Warranty verified", {
                valid: true,
                warranty_code: customerRegistration.warranty_code,
                product_name: linkedCode?.product_name || customerRegistration.product_name || "Product",
                status: linkedCode?.warranty_code_status || "Active",
                is_registered: true,
                is_expired: isExpired,
                days_left: daysLeft,
                warranty_from: warrantyFrom ? warrantyFrom.toISOString() : null,
                warranty_to: warrantyTo ? warrantyTo.toISOString() : null,
                warranty_days: warrantyDays,
                warranty_period_readable: linkedCode?.warranty_period_readable || (warrantyDays ? `${warrantyDays} Days` : null),
                provider_id: customerRegistration.provider?.id,
                provider_name: customerRegistration.provider?.company_name,
                provider_logo: customerRegistration.provider?.company_logo,
                serial_no: linkedCode?.serial_no || customerRegistration.serial_number,
                registration_date: customerRegistration.date_of_installation || customerRegistration.created_at,
                customer_name: `${customerRegistration.first_name || ''} ${customerRegistration.last_name || ''}`.trim(),
            });
        }

        logger.info(`verifyByCodeEndpoint - Code not found in any table`);
        return returnError(res, StatusCodes.NOT_FOUND, "Warranty code not found. Please check the code and try again.");
        
    } catch (error) {
        logger.error(`verifyByCodeEndpoint error: ${error}`);
        return returnError(res, StatusCodes.INTERNAL_SERVER_ERROR, "Failed to verify warranty");
    }
};

export { verifyByCodeEndpoint };
